services:
  tixora.bootstraper:
    image: tixora.bootstraper
    container_name: tixora_api
    build:
      context: .
      dockerfile: src/API/Tixora.Bootstraper/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://localhost:8081;https://localhost:8080
    depends_on:
      - tixora.db

  tixora.db:
    image: postgres:latest
    container_name: tixora_db
    environment:
      - POSTGRES_DB=Tixora
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  tixora.seq:
    image: datalust/seq
    container_name: tixora_seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - 5341:80
    
  tixora.redis:
    image: redis:latest
    container_name: tixora_redis
    ports:
      - 6379:6379