<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
      <ProjectReference Include="..\..\..\Shared\Tixora.Shared.Infrastructure\Tixora.Shared.Infrastructure.csproj" />
      <ProjectReference Include="..\Events.Application\Events.Application.csproj" />
      <ProjectReference Include="..\Events.Domain\Events.Domain.csproj" />
      <ProjectReference Include="..\Events.PublicApi\Events.PublicApi.csproj" />
    </ItemGroup>

</Project>
