<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.1.0" />
      <PackageReference Include="Serilog" Version="4.3.2-dev-02430" />
      <PackageReference Include="Dapper" Version="2.1.72" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tixora.Shared.Domain\Tixora.Shared.Domain.csproj" />
    </ItemGroup>

</Project>
