<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- https://stackoverflow.com/questions/59873726/iendpointroutebuilder-interface-not-found -->
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tixora.Shared.Application\Tixora.Shared.Application.csproj" />
    </ItemGroup>
    
</Project>
