<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="14.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Tixora.Shared.Api\Tixora.Shared.Api.csproj" />
      <ProjectReference Include="..\Tickets.Application\Tickets.Application.csproj" />
      <ProjectReference Include="..\Tickets.Infrastructure\Tickets.Infrastructure.csproj" />
    </ItemGroup>

</Project>
